"""
Tahrifat sinyali tespiti / Tamper signal detection.

StructureReport'u alır, adli sinyalleri (findings) üretir. Her sinyal:
  code, severity (info/low/medium/high/critical), category, weight, tr, en, detail

Ayrıca belge tipini sınıflandırır: digital_native / hybrid / image_only / scanned.

Skorlama scoring.py'de yapılır; burada yalnızca kanıt toplanır.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from pdf_structure import StructureReport, classify_producer

SEVERITY_ORDER = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}


@dataclass
class Finding:
    code: str
    severity: str          # info | low | medium | high | critical
    category: str          # metadata | structure | fonts | content | image | ai
    weight: int            # skora etkisi (ceza puanı)
    tr: str
    en: str
    detail: str = ""

    def as_dict(self, lang: str = "tr") -> dict:
        return {
            "code": self.code,
            "severity": self.severity,
            "category": self.category,
            "weight": self.weight,
            "message": self.tr if lang == "tr" else self.en,
            "detail": self.detail,
        }


def classify_doc_type(s: StructureReport, text_len: int) -> str:
    """
    Belge tipini sınıflandırır.
      digital_native : metin + vektör içerikli gerçek dijital dekont
      hybrid         : hem gömülü görsel hem seçilebilir metin
      image_only     : içinde sadece görsel var, metin yok (foto/screenshot)
      scanned        : tek büyük görsel, taranmış belge
    """
    biggest = max((i["width"] * i["height"] for i in s.images), default=0)
    page_area = 0
    if s.page_sizes:
        w, h = s.page_sizes[0]
        # PDF birimini piksele kabaca çevir (150 dpi varsayımı)
        page_area = (w / 72 * 150) * (h / 72 * 150)
    big_image = page_area and biggest >= 0.45 * page_area

    if text_len < 40:
        # neredeyse hiç metin yok
        if s.image_count >= 1 and big_image:
            return "scanned"
        return "image_only"
    if text_len >= 40 and s.image_count >= 1 and big_image:
        return "hybrid"
    if s.image_count >= 1 and text_len >= 40 and not big_image:
        # metin + küçük logo/mühür görselleri (tipik banka dekontu)
        return "digital_native"
    return "digital_native"


def detect(s: StructureReport, text_len: int, doc_type: str) -> list[Finding]:
    F: list[Finding] = []
    cp = classify_producer(s.producer, s.creator)

    # ---------------------------------------------------------------
    # 1) ÜRETİCİ/OLUŞTURUCU TUTARSIZLIĞI — düzenleyici yazılım izi
    # ---------------------------------------------------------------
    if cp["editor_hits"]:
        # Bir üretim aracı (JasperReports vb.) tarafından oluşturulmuş ama
        # sonradan bir düzenleyici (Quartz/Preview vb.) tarafından yeniden
        # kaydedilmişse bu güçlü bir oynama işaretidir.
        gen = cp["generator_hits"]
        for hit in cp["editor_hits"]:
            if gen:
                F.append(Finding(
                    "PRODUCER_RESAVE", "high", "metadata", 30,
                    tr=f"Belge önce bir üretim sistemi ({', '.join(gen)}) tarafından oluşturulmuş, "
                       f"ardından farklı bir yazılımla yeniden kaydedilmiş: {hit['desc']}. "
                       f"Banka dekontları yeniden kaydedilmez; bu, belgenin bir editörden geçtiğini gösterir.",
                    en=f"Document was first generated by a reporting system ({', '.join(gen)}) then "
                       f"re-saved by another tool: {hit['desc']}. Genuine bank receipts are not re-saved.",
                    detail=f"Creator={s.creator} | Producer={s.producer}",
                ))
            else:
                F.append(Finding(
                    "EDITOR_PRODUCER", "medium", "metadata", 18,
                    tr=f"Üretici bilgisi bir düzenleme/dışa aktarma aracına işaret ediyor: {hit['desc']}.",
                    en=f"Producer indicates an editing/export tool: {hit['desc']}.",
                    detail=f"Producer={s.producer}",
                ))

        # Tarayıcı motoru (Skia/Chromium): banka dekontlarında OLAĞAN üretim biçimi.
        # Yalnızca önce bir üretim sistemi varsa (sonra tarayıcıyla yeniden basılmış) şüphelidir.
        for hit in cp.get("browser_hits", []):
            if gen:
                F.append(Finding(
                    "PRODUCER_RESAVE", "high", "metadata", 30,
                    tr=f"Belge önce bir üretim sistemi ({', '.join(gen)}) tarafından oluşturulmuş, "
                       f"ardından tarayıcı motoruyla yeniden basılmış: {hit['desc']}. Banka dekontları "
                       f"yeniden kaydedilmez; bu, belgenin bir düzenlemeden geçtiğini gösterir.",
                    en=f"Document was first generated by a reporting system ({', '.join(gen)}) then "
                       f"re-rendered by a browser engine: {hit['desc']}.",
                    detail=f"Creator={s.creator} | Producer={s.producer}",
                ))
            else:
                F.append(Finding(
                    "BROWSER_RENDERED", "info", "metadata", 0,
                    tr=f"Belge tarayıcı motoruyla üretilmiş: {hit['desc']}. Bu, birçok bankanın "
                       f"mobil/İnternet şubesi dekontlarında olağan üretim biçimidir ve tek başına "
                       f"tahrifat işareti DEĞİLDİR.",
                    en=f"Document produced by a browser engine: {hit['desc']}. This is the normal way "
                       f"many banks render mobile/online receipts and is NOT a tampering signal by itself.",
                    detail=f"Producer={s.producer}",
                ))

    # ---------------------------------------------------------------
    # 2) APPENDMODE — artımlı kayıt işareti (Producer içinde)
    # ---------------------------------------------------------------
    if cp["append_mode"]:
        F.append(Finding(
            "APPEND_MODE", "high", "structure", 22,
            tr="Üretici bilgisinde 'AppendMode' var — belge, orijinal oluşturulduktan sonra "
               "üzerine ekleme yapılarak (incremental) yeniden kaydedilmiş.",
            en="Producer string contains 'AppendMode' — the file was saved incrementally on top of the original.",
            detail=s.producer,
        ))

    # ---------------------------------------------------------------
    # 3) INCREMENTAL UPDATES — birden fazla %%EOF / xref revizyonu
    # ---------------------------------------------------------------
    if s.has_incremental_updates:
        sev = "high" if s.incremental_updates >= 2 else "medium"
        w = 24 if s.incremental_updates >= 2 else 16
        F.append(Finding(
            "INCREMENTAL_UPDATE", sev, "structure", w,
            tr=f"Belgede {s.incremental_updates} adet artımlı güncelleme (ek revizyon) tespit edildi "
               f"({s.eof_count} adet %%EOF işareti). Bu, belgenin oluşturulduktan sonra en az bir kez "
               f"kaydedilip değiştirildiğini gösterir. Dijital imzalı bankacılık belgeleri normalde tek revizyonludur.",
            en=f"{s.incremental_updates} incremental update(s) detected ({s.eof_count} %%EOF markers). "
               f"The file was modified and re-saved at least once after creation.",
            detail=f"eof={s.eof_count}, startxref={s.startxref_count}, /Prev offsets={s.trailer_prev_offsets}",
        ))

    # ---------------------------------------------------------------
    # 4) TARİH ANOMALİLERİ
    # ---------------------------------------------------------------
    is_aem = any(g in ("adobe experience manager", "adobe livecycle") for g in cp["generator_hits"])
    if s.creation_dt and s.mod_dt:
        delta = (s.mod_dt - s.creation_dt).total_seconds()
        if delta < -60:
            F.append(Finding(
                "MOD_BEFORE_CREATE", "high", "metadata", 20,
                tr=f"Değiştirilme tarihi ({s.mod_dt}) oluşturulma tarihinden ({s.creation_dt}) ÖNCE. "
                   f"Bu fiziksel olarak imkânsızdır ve metadata ile oynandığını gösterir.",
                en=f"Modification date ({s.mod_dt}) is BEFORE creation date ({s.creation_dt}) — physically impossible.",
                detail=f"delta={delta}s",
            ))
        # Not: oluşturma↔değiştirme farkı artık timing.py'de (daha ayrıntılı) ele alınır.
    if is_aem and s.creation_dt and s.creation_dt.year <= 2018:
        F.append(Finding(
            "AEM_TEMPLATE_DATE", "info", "metadata", 0,
            tr=f"Oluşturulma tarihi ({s.creation_dt.date()}) form şablonunun tarihidir (Adobe AEM forms). "
               f"Bu normaldir; işlem tarihi belge içeriğindeki tarihtir.",
            en=f"Creation date ({s.creation_dt.date()}) is the form template date (Adobe AEM). This is expected.",
            detail=f"Producer={s.producer}",
        ))

    # XMP ile Info sözlüğü tarih tutarsızlığı
    if s.xmp_present and s.xmp_modify_date and s.mod_date:
        if _norm_date(s.xmp_modify_date) and _norm_date(s.mod_date) and \
           _norm_date(s.xmp_modify_date) != _norm_date(s.mod_date):
            F.append(Finding(
                "XMP_INFO_MISMATCH", "medium", "metadata", 12,
                tr="XMP metadata ile belge bilgi sözlüğündeki (Info) tarihler uyuşmuyor — "
                   "bu tutarsızlık genellikle metadata'nın elle düzenlendiğini gösterir.",
                en="XMP metadata date differs from the Info dictionary date — a common sign of hand-edited metadata.",
                detail=f"xmp={s.xmp_modify_date} info={s.mod_date}",
            ))

    # ---------------------------------------------------------------
    # 5) XMP HISTORY — düzenleme geçmişi
    # ---------------------------------------------------------------
    for h in s.xmp_history:
        agent = (h.get("agent") or "").lower()
        act = (h.get("action") or "").lower()
        if any(k in agent for k in ("photoshop", "acrobat", "illustrator", "gimp", "preview", "word")):
            F.append(Finding(
                "XMP_EDIT_HISTORY", "high", "metadata", 20,
                tr=f"XMP düzenleme geçmişinde bir editör kaydı var: '{act}' — {h.get('agent')}. "
                   f"Belge bir görsel/PDF editöründen geçmiş.",
                en=f"XMP history shows an editor event: '{act}' — {h.get('agent')}.",
                detail=str(h),
            ))

    # ---------------------------------------------------------------
    # 6) FONT TUTARSIZLIĞI — aynı fontun birden çok alt kümesi
    # ---------------------------------------------------------------
    base_families: dict[str, int] = {}
    for f in s.fonts:
        bf = f.get("basefont", "")
        fam = re.sub(r"^[A-Z]{6}\+", "", bf)  # subset ön ekini at
        base_families[fam] = base_families.get(fam, 0) + 1
    multi_subset = {fam: n for fam, n in base_families.items() if n >= 2 and fam}
    if multi_subset:
        worst = max(multi_subset.values())
        sev = "medium" if worst >= 2 else "low"
        F.append(Finding(
            "FONT_MULTI_SUBSET", sev, "fonts", 14,
            tr=f"Aynı yazı tipinin birden çok alt kümesi gömülü: {multi_subset}. "
               f"Bir belgeye sonradan metin eklendiğinde (ör. tutar/isim değişimi), düzenleme aracı "
               f"aynı fontu ikinci kez ve farklı bir alt kümeyle gömer. Bu, metin düzenlemesinin klasik izidir.",
            en=f"Multiple subsets of the same font are embedded: {multi_subset}. "
               f"Re-editing text (e.g. changing an amount) makes an editor embed a second subset of the same font.",
            detail=str(base_families),
        ))

    # Gömülü olmayan font (dijital dekontta beklenmez)
    non_embedded = [f["basefont"] for f in s.fonts if not f["embedded"] and f["basefont"]]
    if non_embedded and doc_type in ("digital_native", "hybrid"):
        F.append(Finding(
            "FONT_NOT_EMBEDDED", "low", "fonts", 6,
            tr=f"Gömülü olmayan yazı tipi(leri) var: {non_embedded}. "
               f"Kurumsal dekontlarda tüm fontlar genelde gömülüdür.",
            en=f"Non-embedded font(s) present: {non_embedded}.",
            detail="",
        ))

    # ---------------------------------------------------------------
    # 7) ANNOTATION / ACROFORM — üzerine eklenen içerik
    # ---------------------------------------------------------------
    if s.annotation_count > 0 and doc_type in ("digital_native", "hybrid"):
        F.append(Finding(
            "ANNOTATIONS_PRESENT", "low", "content", 8,
            tr=f"Belgede {s.annotation_count} adet not/annotation nesnesi var. Nihai bir dekontta "
               f"bulunmaması beklenir; üzerine eklenmiş içerik olabilir.",
            en=f"{s.annotation_count} annotation object(s) present — unexpected on a finalized receipt.",
            detail="",
        ))
    if s.js_present:
        F.append(Finding(
            "JS_PRESENT", "medium", "structure", 12,
            tr="Belgede JavaScript var. Statik bir dekontta JavaScript beklenmez; dinamik içerik/oynama riski.",
            en="Document contains JavaScript — unexpected in a static receipt.",
            detail="",
        ))

    # ---------------------------------------------------------------
    # 8) İMZA DURUMU
    # ---------------------------------------------------------------
    if s.has_signature:
        F.append(Finding(
            "HAS_SIGNATURE", "info", "structure", -10,   # negatif = güven artırıcı
            tr="Belge dijital imza içeriyor. İmzanın kapsamı ayrıca doğrulanmalıdır.",
            en="Document contains a digital signature (coverage should be verified).",
            detail="",
        ))

    # ---------------------------------------------------------------
    # 9) BELGE TİPİNE ÖZGÜ NOTLAR
    # ---------------------------------------------------------------
    if doc_type in ("image_only", "scanned"):
        F.append(Finding(
            "IMAGE_ONLY_DOC", "info", "content", 0,
            tr="Belge içinde seçilebilir metin yok; içerik tek bir görselden ibaret. "
               "Bu tür belgelerde yapısal metin analizi yapılamaz; değerlendirme OCR ve görsel adli "
               "analizle sınırlıdır. Fotoğraf/ekran görüntüsü kolayca düzenlenebildiğinden güven düşüktür.",
            en="No selectable text; content is a single image. Structural text analysis is not possible; "
               "assessment relies on OCR and image forensics. Photos/screenshots are easy to alter, lowering trust.",
            detail=f"doc_type={doc_type}",
        ))

    return F


def _norm_date(raw: str) -> str:
    if not raw:
        return ""
    digits = re.sub(r"\D", "", str(raw))
    return digits[:12]
